name: CI Check
on: 
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:
jobs:
  clean-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']
    services:
      docker:
        image: docker:24.0.0
        options: --privileged
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Getting repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@f292bcf206fce7262eb4f1e6dca4b969c656883e
      with:
        auto-activate-base: false
        activate-environment: test-env
        python-version: 3.11
        channels: conda-forge
        channel-priority: strict
        miniforge-variant: Mambaforge
        use-mamba: true

    - name: Install dependencies (with conda, for xesmf)
      run: |
        mamba install -y esmpy xesmf

    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system -e .[dev]

    - name: Create .cdsapirc file
      run: |
        echo "url: https://cds.climate.copernicus.eu/api" >> ~/.cdsapirc
        echo "key: ${{ secrets.CDSAPI_KEY }}" >> ~/.cdsapirc

    - name: Execute PyTest
      run: |
        python -m pytest -svv --cov=heiplanet_data --cov-report=xml:heiplanet_data/coverage_re/coverage.xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./heiplanet_data/coverage_re/